export const buttonPressAudio = new Audio('./assets/button-press.wav')
export const kitchenTimer = new Audio('./assets/kichen-timer.mp3')
export const Lareira = new Audio('./assets/Lareira.wav')
export const Floresta = new Audio('./assets/Floresta.wav')
export const Cafeteria = new Audio('./assets/Cafeteria.wav')
export const Chuva = new Audio('./assets/Chuva.wav')